#!/usr/bin/env ruby

require "visualize_activities"
require "thor"
require 'time'

class VisualizeActivitiesCLI < Thor
  desc 'exec target_date', 'fetch issues activities'
  def exec(target_date)
    VisualizeActivities.execute(Time.parse(target_date))
  end
end

VisualizeActivitiesCLI.start(ARGV)
